"""initial schema

Revision ID: 0e58fe12b069
Revises: 
Create Date: 2026-09-16 16:06:14.921707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e58fe12b069'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EGAS',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('API_file', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('max_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('partner_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('contact_details', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonus',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('promocode', sa.String(length=255), nullable=False),
    sa.Column('need_experience', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educational_institution',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('EI_with_EGAS',
    sa.Column('EI_id', sa.Integer(), nullable=False),
    sa.Column('EGAS_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EGAS_id'], ['EGAS.id'], ),
    sa.ForeignKeyConstraint(['EI_id'], ['educational_institution.id'], ),
    sa.PrimaryKeyConstraint('EI_id', 'EGAS_id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('patronymic', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('student_group', sa.String(length=255), nullable=False),
    sa.Column('max_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('EI_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EI_id'], ['educational_institution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_bonus',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('bonus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bonus_id'], ['bonus.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'bonus_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_bonus')
    op.drop_table('student')
    op.drop_table('EI_with_EGAS')
    op.drop_table('educational_institution')
    op.drop_table('city')
    op.drop_table('bonus')
    op.drop_table('subject')
    op.drop_table('partner')
    op.drop_table('applications')
    op.drop_table('admins')
    op.drop_table('EGAS')
    # ### end Alembic commands ###
